name: Docker Deployment

on:
  push:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Login to docker
      uses: docker/login-action@v3.0.0
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and publish Image
      uses: bitovi/github-actions-docker-publish@v1.0.7
      with:
        org_name: lourash
        repo_name: sample-cicd-docker
        docker_username: lourash
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
